spring:
  profiles:
    active: prod
  jackson:
    default-property-inclusion: non_null
  servlet:
    multipart:
      max-file-size: 4MB
      max-request-size: 5MB

cache-expire-second: 600
cache-prefix:
  picture: "picture:id:"

mybatis:
  type-aliases-package: com.a205.mybed.pictureservice.pojo
  mapper-locations: classpath:mapper/*.xml
